// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Pickup.h"
#include "Engine/NavigationObjectBase.h"
#include "PickupGenerator.generated.h"

/**
 * APickupGeneratePoint
 *
 * Generate Pickup regularly.
 * Only exist on the server.
 * Only use to Generate Pickup. Monster's death can use this to generate pickup as well. 
 * Pickup is not only generated by this actor. e.g. when player dies, their weapon will become pickups.
 */
UCLASS(Blueprintable, ClassGroup=Alive, hidecategories=Collision)
class ALIVE_API APickupGenerator : public ANavigationObjectBase
{
	GENERATED_BODY()

public:
	APickupGenerator();

	void DestroyAfterNextGenerate() { bLoop = false; }
	bool HasPickupNow() const { return bHasPickup; }
protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	UPROPERTY(EditAnywhere, Category="Alive|Pickup")
	TArray<TSubclassOf<APickup>> PickupList;

	// If false, this generator will be destroyed after generating the next pickup.
	UPROPERTY(EditAnywhere, Category="Alive|Pickup")
	bool bLoop;

	// Count since generator lost it's pickup (be picked up or time out).
	UPROPERTY(EditAnywhere, Category="Alive|Pickup")
	float GenerateCooldown;
	
private:
	FTimerHandle NextPickupGenerateTimerHandle;

	bool bHasPickup;
	void GeneratePickup();
	void OnPickUpOrTimeOutEvent();
};
